#
# Vivado (TM) v2015.2 (64-bit)
#
# create_project.tcl: Tcl script for re-creating project 'p1300c'
#
# Generated by Vivado on Sun Mar 13 19:40:09 +0300 2016
# IP Build 1264090 on Wed Jun 24 14:22:01 MDT 2015
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "E:/users/tasha/git_dirs/refactor/FpgaOpenCV/fpga/DevelProject/projects_/p1300c/p1300c.srcs/sources_1/bd/p1300c/p1300c.bd"
#    "E:/users/tasha/git_dirs/refactor/FpgaOpenCV/fpga/DevelProject/projects_/p1300c/p1300c.srcs/sources_1/bd/p1300c/hdl/p1300c_wrapper.vhd"
#    "E:/users/tasha/git_dirs/refactor/FpgaOpenCV/fpga/DevelProject/src_/xdc/embv_python1300.xdc"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************



# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
  create_run -name synth_1 -part xc7z020clg400-1 -flow {Vivado Synthesis 2015} -strategy "Vivado Synthesis Defaults" -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2015" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property "part" "xc7z020clg400-1" $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
  create_run -name impl_1 -part xc7z020clg400-1 -flow {Vivado Implementation 2015} -strategy "Vivado Implementation Defaults" -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2015" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property "part" "xc7z020clg400-1" $obj
set_property "steps.write_bitstream.args.readback_file" "0" $obj
set_property "steps.write_bitstream.args.verbose" "0" $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

update_compile_order -fileset sources_1
update_compile_order -fileset sim_1
save_bd_design
launch_runs impl_1 -to_step write_bitstream

puts "INFO: Project created:p1300c"

while {1} {
   # stop if end of run detected
   if {[file exists p1300c.runs/impl_1/.vivado.end.rst]} { 
      puts "Found End of Bitstream Creation..."
      break 
   }
# wait 1 second to check
after 1000   
} 

set sdk "xsdk"
puts "Attempting to Build SDK..."
exec  xsdk -batch -source ../../software_/p1300c_sdk.tcl -notrace
puts "Generating BOOT.BIN..."
exec  bootgen -image ../../software_/p1300c_sd.bif -w -o BOOT.bin
